### ISSUE TITLE
 Segmentaton fault(core dumped)

### ISSUE THREAD

**Issue by laoniu2020** [mxcube/mxcube3#864] opened 2020-10-19 14:24 UTC
When I run 
  `python mxcube3-server -r test/HardwareObjectsMockup.xml --log-file mxcube3.log`
I got error:
![image](https://user-images.githubusercontent.com/577581/96463593-73da2e80-1259-11eb-8d99-c3a402a9ecb7.png)

Other info:
Centos7.8 
Python3.7

[root@localhost mxcube3]# pip3 list

> Package            Version
> ------------------ ---------
> cachelib           0.1.1
> certifi            2020.6.20
> chardet            3.0.4
> click              7.1.2
> cycler             0.10.0
> Flask              1.1.2
> Flask-Session      0.3.2
> Flask-SocketIO     4.3.1
> funcsigs           1.0.2
> gevent             1.4.0
> gevent-websocket   0.10.1
> gipc               1.1.0
> greenlet           0.4.17
> idna               2.10
> importlib-metadata 2.0.0
> itsdangerous       1.1.0
> Jinja2             2.11.2
> jsonpickle         1.4.1
> kiwisolver         1.2.0
> Louie-latest       1.3.1
> lxml               4.6.1
> MarkupSafe         1.1.1
> matplotlib         3.3.2
> mock               4.0.2
> nose               1.3.7
> numpy              1.19.2
> pbr                5.5.0
> Pillow             8.0.0
> pip                20.2.4
> pyasn1             0.4.8
> pyasn1-modules     0.2.8
> pyparsing          2.4.7
> python-dateutil    2.8.1
> python-engineio    3.13.2
> python-ldap        3.3.1
> python-socketio    4.6.0
> redis              3.5.3
> requests           2.24.0
> ruamel.yaml        0.16.12
> ruamel.yaml.clib   0.2.2
> scandir            1.10.0
> scipy              1.5.3
> setuptools         40.8.0
> six                1.15.0
> suds-py3           1.4.1.0
> urllib3            1.25.10
> v4l2               0.2
> Werkzeug           1.0.1
> zipp               3.3.1
> zope.event         4.5.0
> zope.interface     5.1.2

Any suggestions?
Thanks!

**Comment by laispc** [comment] 2020-10-21 20:15
I am fighting with the same bug.

**Comment by laispc** [comment] 2020-10-21 21:50
Well, I got a quick/temporary fix for this while we don't get the root cause of the bug.
 
I got this error when I rebuild my mxcube3 container from the scratch. As I had the same container already running on other machine, I exported its conda env to yml and recreated it on the new container. It worked.

I am attaching here the .yml I used. Steps:

* Deactivate current env: `conda deactivate`
* Remove current mxcube env: `conda remove -n mxcube`
* Recreate env: `conda env create -f requirements.yml`

Hope it helps while we check for a final solution.
[requirements.zip](https://github.com/mxcube/mxcube3/files/5418854/requirements.zip)

**Comment by marcus-oscarsson** [comment] 2020-10-22 07:16
Hm, this is actually a problem with something within HardwareReposiotry it seems like a recent update of a dependency is causing this issue, we are trying to figure out which one. We don't know which dependency at the moment but we are working on identifying it.

**Comment by marcus-oscarsson** [comment] 2020-10-22 10:03
It seemed like that the latest greenlet version causes this issue, ive pinned it to 0.4.16, which seems to work here. Could you confirm that as well ?

**Comment by laispc** [comment] 2020-10-23 16:09
Hi, @marcus-oscarsson ! I tested greenlet==0.4.16 with current master of mxucbe3 and it worked, thanks a lot!

However, by getting the latest auto built container, the errors remains. I had to install greenlet==0.4.16 to make it work. 
Probably it is because the container runs with conda, so maybe the pinned version should be added to **conda-environment.yml** too.

Running this fixed environment with my mxcube3/HWR fork now gives me other errors, but I am still checking if it is not something from my side. : )

**Comment by laispc** [comment] 2020-10-23 20:40
My fork is still not running (with current requirements neither with the ones I have on the other machine). I am getting errors like the following one. Have you ever seen this one? Any ideas for debugging it? I am using just the mockup xmls.

```
2020-10-23 17:33:27,242 |exceptions|ERROR  | Uncaught exception while calling /mxcube/api/v0.1/beamline/
Traceback (most recent call last):
  File "/opt/conda/envs/mxcube/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/mxcube/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/envs/mxcube/lib/python3.7/site-packages/flask/helpers.py", line 1084, in send_static_file
    self.static_folder, filename, cache_timeout=cache_timeout
  File "/opt/conda/envs/mxcube/lib/python3.7/site-packages/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

```

Thanks in advance.

**Comment by marcus-oscarsson** [comment] 2020-10-23 20:49
Good evening, or afternoon ... :)

I think its because you have no static files build or development server running ?

`send_static_file` somehow indicates that there is a file missing, could you check so that the contents in mxcube3/static
looks good ?

I'll close this issue as its not directly related to the original issue, but feel free to reopen it in case I'm wrong or open another one :)

**Closed** 2020-10-23 20:49 UTC

**Comment by laispc** [comment] 2020-10-23 22:13
Good evening, @marcus-oscarsson !

I run the dev server and got no mxcube3/static folder.
Then I tried to run the production version instead (npm run build) and the static folder was created. But now there is nothing running on localhost:8090. mxcube3/static looks like this:

```
1cae45989275e1ad4e956e92a9fd08ff.ogv
-rw-r--r--  1 root root    78737 Oct 23 18:50 5f4164edee3a93d7c577722fd59dc454.gif
-rw-r--r--  1 root root   165742 Oct 23 18:50 674f50d287a8c48dc19ba404d20fe713.eot
-rw-r--r--  1 root root   387830 Oct 23 18:50 760bd83ee04dff470e0277f3eb7deebe.svg
-rw-r--r--  1 root root    25314 Oct 23 18:50 7d6298bc6c52df32dcdc5706c5bd862c.png
-rw-r--r--  1 root root 15184088 Oct 23 18:50 8a9853e0395b8ce408e9312f143ca9c0.ogv
-rw-r--r--  1 root root     3208 Oct 23 18:50 a51c5608d01acf32df728f299767f82b.gif
-rw-r--r--  1 root root   165548 Oct 23 18:50 b06871f281fee6b241d60582ae9369b9.ttf
-rw-r--r--  1 root root     5943 Oct 23 18:50 c3437d3371f119024def49ac75d53fe4.png
-rw-r--r--  1 root root 34866261 Oct 23 18:50 e9b1dc2cd9cf3db3a3946d6f766cb64e.ogv
-rw-r--r--  1 root root    93878 Oct 23 18:50 f0ea477ef046ba5fef9249ec3172903e.svg
-rw-r--r--  1 root root     3710 Oct 23 18:50 favicon.ico
-rw-r--r--  1 root root      326 Oct 23 18:50 index.html
-rw-r--r--  1 root root  3144603 Oct 23 18:50 main.js
```

**Comment by marcus-oscarsson** [comment] 2020-10-26 07:24
Hi @laispc 

I think Ill send you an email instead :)

Marcus
